#!/bin/bash

## MeaTLoTioN's MRC announce script v2.0
## Released: 2021-03-27 21:00:00 UTC
##
## DO NOT edit this file, only edit ml-mrcannounce.conf

### greetz ###
# ktulu, paulie420, stackfault, roovis, crewmate, smooth, hawkhubbard, xqtr
# the godfather, apam, systemd, anachronist, maxmouse, warmfuzzy, avon, black panther
# cranksy, gryphon, nuskooler, ripuk, shinobi, cr1mson, fu, g00r00
### no particular order ###

if [[ $# -lt 1 ]]; then
  echo "$(date) ml-mrcannounce ERROR: Not enough arguments. Aborting." >> /var/log/ml-mrcannounce.log
  echo "Not enough arguments, aborted."
  exit 1
else
  . $SCRIPTS/ml-mrcannounce.conf
  HANDLE=$1
  RRESPC=${#RRESP[@]}
  RNUM=$(echo $((1 + $RANDOM % $RRESPC)) )
  RCHOICE=${RRESP[$(($RNUM-1))]}
  MRCANNOUNCE="$BOTUSER~$BBSNAME~$ROOM~~~~|15* |13$HANDLE |14$RCHOICE $BBSDISP~\r\n"
  echo "$MRCANNOUNCE" > $MRCDATA/mrcannounce.mrc
fi
