@ECHO OFF

SET HANDLE=%1
SET MRCDATA=C:\MYSTIC\DATA\MRC
SET BBSNAME=Unspecified_BBS
SET BBSDISP=^|11U^|03nspecified ^|11B^|03BS
SET BOTUSER=SysOp
SET ROOM=lobby

SET MRCANNOUNCE="%BOTUSER%~%BBSNAME%~%BBSROOM%~~~~|15* |13%HANDLE% |14has just logged into %BBSDISP%~\r\n"

ECHO %MRCANNOUNCE% > %MRCDATA%\test.mrc

